Game logic Completion
Aaron-RN/Ruby-Tic-Tac-Toe pull request #4
Opened 2019-10-09 22:37 UTC by Aaron-RN

2019-10-10 09:08 UTC, bolah2009 requested changes
## Nice user interface :clap: 

Please check out the comments below and make changes, also, let's try and keep the one class from doing another class function.

#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-10-10 09:08 UTC, bolah2009 commented on lib/game_logic.rb
> +    puts 'DRAW!'.bold.underline,"\n" if @turns_taken >= @max_turns
Let's keep user interaction away from game logic.

> `main.rb` file should be responsible for user interaction. This is the only one place where `puts` and `get.chomp` can be used.

2019-10-10 09:08 UTC, bolah2009 commented on lib/game_logic.rb
> +class Player
Can we move this `Player class` to a new file instead? Maybe `player.rb`... :thinking:

2019-10-11 12:56 UTC, BalintMendli approved these changes
Hi @Aaron-RN @zhuchini ,

Great job implementing requested changes. 👏 

### 👍 

Status: **Approved**

2019-10-16 19:30 UTC, merged